const dailyAstrology = [
  "Today is a great day for communication and networking. Reach out to old friends or colleagues.",
  "You may encounter some unexpected financial opportunities today. Stay open-minded.",
  "Focus on self-care today. Take time to relax and recharge your batteries.",
  "Your intuition is heightened today. Trust your gut instincts in decision-making.",
  "You may feel a strong urge to explore new ideas and philosophies today. Embrace intellectual growth.",
  "Pay attention to your dreams tonight. They may hold valuable insights for you.",
  "You may receive recognition or praise for your hard work today. Enjoy the spotlight.",
  "Be open to collaboration today. Working with others can lead to great success.",
  "You may feel a sense of restlessness today. Try to channel that energy into something productive.",
  "Today is a good day to focus on your long-term goals and aspirations. Set intentions for the future.",
  "You may feel a strong emotional connection to loved ones today. Express your feelings openly.",
  "Stay grounded today and focus on practical matters. Attend to any pressing responsibilities.",
  "You may feel inspired to pursue a creative project today. Follow your muse.",
  "Take time to connect with nature today. Spending time outdoors can be very rejuvenating.",
  "You may receive unexpected news or information today. Stay flexible and adapt to changes.",
  "Focus on maintaining balance in all areas of your life today. Avoid extremes.",
  "Trust your instincts when it comes to relationships today. Your intuition will guide you.",
  "You may feel a strong sense of purpose today. Use that energy to make positive changes.",
  "Today is a good day for introspection and self-reflection. Take stock of where you are and where you want to be.",
  "You may feel a desire to break free from routine today. Embrace spontaneity and adventure.",
  "You may encounter some challenges today, but trust that you have the strength to overcome them.",
  "Focus on building strong foundations today. Lay the groundwork for future success.",
  "You may feel a strong sense of empathy and compassion today. Reach out to those in need.",
  "Trust in the timing of the universe today. Everything is unfolding exactly as it should.",
  "You may feel a sense of wanderlust today. Allow yourself to explore new horizons.",
  "Focus on gratitude today. Count your blessings and appreciate the abundance in your life.",
  "You may feel a strong connection to your spiritual beliefs today. Take time to nurture your soul.",
  "Today is a good day to focus on your health and well-being. Take steps to nourish your body and mind.",
  "You may feel a sense of clarity and purpose today. Trust that you are on the right path.",
  "Focus on fostering deeper connections with others today. Open your heart and share your truth.",
  "You may feel a sense of excitement and anticipation today. Embrace new opportunities with enthusiasm.",
  "Today is a good day to focus on personal growth and development. Invest in yourself.",
  "You may feel a sense of liberation today. Let go of anything that is holding you back.",
  "Trust in the power of manifestation today. Your thoughts have the power to shape your reality.",
  "You may feel a strong desire for independence today. Take ownership of your life and choices.",
  "Focus on finding balance between work and play today. Take time to enjoy the simple pleasures.",
  "You may feel a sense of renewal and rebirth today. Embrace new beginnings with an open heart.",
  "Today is a good day to focus on your finances. Take steps to secure your financial future.",
  "You may feel a sense of harmony and peace today. Surround yourself with positive energy.",
  "Trust in divine timing today. Everything is happening exactly as it should.",
  "You may feel a sense of empowerment today. Take control of your destiny.",
  "Focus on releasing old patterns and beliefs today. Clear space for new growth.",
  "You may feel a sense of adventure and excitement today. Follow your passions wherever they may lead.",
  "Today is a good day to focus on relationships. Strengthen bonds with loved ones.",
  "You may feel a strong sense of determination today. Trust in your ability to achieve your goals.",
  "Stay open to new experiences today. The universe may have some surprises in store for you.",
  "You may feel a sense of inspiration and creativity today. Channel that energy into your projects.",
  "Focus on self-expression today. Allow your authentic voice to shine through.",
  "You may feel a sense of inner peace and contentment today. Trust that you are exactly where you need to be.",
  "Today is a good day to focus on personal healing. Release any past traumas or wounds.",
  "You may feel a strong connection to your intuition today. Trust your inner guidance.",
  "Focus on gratitude and appreciation today. Count your blessings and cultivate a positive mindset.",
  "You may feel a sense of clarity and vision today. Trust in your ability to manifest your dreams.",
  "Stay open to new possibilities today. The universe may have some surprises in store for you.",
  "You may feel a sense of alignment and purpose today. Trust that you are on the right path.",
  "Focus on nurturing your relationships today. Spend quality time with loved ones.",
  "You may feel a sense of empowerment and confidence today. Step into your personal power.",
  "Trust in the process of transformation today. Embrace change and growth.",
  "You may feel a sense of inspiration and motivation today. Use that energy to pursue your goals.",
  "Focus on cultivating inner peace and tranquility today. Find stillness amidst the chaos.",
  "You may feel a strong sense of intuition and psychic awareness today. Trust your inner wisdom.",
  "Stay open to opportunities for growth and expansion today. The universe is guiding you towards your highest good.",
  "You may feel a sense of liberation and freedom today. Break free from anything that is holding you back.",
  "Focus on living in the present moment today. Let go of worries about the past or future.",
  "You may feel a sense of connection to the divine today. Trust that you are being guided and supported.",
  "Today is a good day to focus on self-care and nurturing. Take time to pamper yourself.",
  "You may feel a sense of excitement and adventure today. Embrace new experiences with an open heart.",
  "Focus on gratitude and appreciation today. Count your blessings and give thanks for all that you have.",
  "You may feel a sense of clarity and insight today. Trust your inner wisdom to guide you.",
  "Stay open to unexpected opportunities today. The universe may have some surprises in store for you.",
  "You may feel a sense of renewal and transformation today. Embrace change and growth.",
  "Focus on cultivating joy and happiness in your life today. Find reasons to smile and laugh.",
  "You may feel a strong sense of purpose and direction today. Trust that you are on the right path.",
  "Trust in the power of manifestation today. Your thoughts have the power to create your reality.",
  "You may feel a sense of empowerment and confidence today. Step into your personal power.",
  "Focus on releasing old patterns and beliefs today. Clear space for new opportunities to come into your life.",
];

const button = document.getElementById("button");
const astrologyBox = document.getElementById("astrologyBox");

button.addEventListener("click", () => {
  let arrayNum = parseInt(Math.random() * dailyAstrology.length);
  console.log(arrayNum);
  astrologyBox.innerHTML = dailyAstrology[arrayNum];
});
